### PR TITLE
Waifu french translation

### PR DESCRIPTION
**Pull request by AntoineKM**
closes: #147
closes: #148

- Add French Translation
- Resolving prettier errors from eslint
- Add GitHub Link to Footer

### CODE REVIEW

**Comment by AntoineKM** [comment]
French translation will probably be over tomorrow

**Comment by chase-manning** [comment]
Wow this is awesome @AntoineKM !!!
Thanks heaps :heart:

Let me know when finished and we will merge for sure 😄

**Comment by AntoineKM** [comment]
@chase-manning i think i'm done!

**Comment by AntoineKM** [comment]
That's why I said "I think"😂

**Comment by chase-manning** [comment]
Thanks @AntoineKM Great PR 😄 
Will let you know if we need anymore fr translations later on if that's okay?

**Pull request merged**
