### PR TITLE
:sparkles: Add "View on Marketplace" Button on WaifuDetail.tsx

### PR DESCRIPTION
**Pull request by andriishupta**
- add translations
- update styles of WaifuDetail
- add AdditionalInfo wrapper for WaifuOwner and ViewOnMarketPlace
- add globals to getMarketplaceLink
- add ViewOnMarketplace.tsx component

### CODE REVIEW

**Comment by andriishupta** [comment]
resolves #119

**Comment by andriishupta** [comment]
*let me know if any visual/code changes should be done

**Comment by chase-manning** [comment]
@andriishupta  Thanks so much for the PR man!!! This is awesome!!! ❤️

**Comment by chase-manning** [comment]
@andriishupta Let me know if you're on the Waifusion discord. I'll give you the contributor role. Also, let me know if you want to help out with the development for our Version 2 series 😄

**Pull request merged**
